### ISSUE TITLE
Rm project directory from github repo

### ISSUE THREAD

**Issue by neelsmith** [hmteditors/hmt20-team10#1]
The `project` directory contains temporary artifacts built by scala for its internal use.  It should not be part of the git repository.

You can now learn the `git rm` command...

**Comment by neelsmith** [comment]
Since this is the first issue for this team, note that when it is resolved, you should add a comment noting that, and then *close and comment* rather than just *comment*

**Comment by MGelein** [comment]
So, the `git rm` command has removed the project from the index it says. I assume this means it is no longer being tracked by git even though I still have a local copy. 

The folder no longer shows up in GitHub so I think everything worked fine. Just a question: What happens if I now pull the repo somewhere else and then recreate the `project` folder (as I assume it also no longer is included in a `pull` command. ).

**Comment by neelsmith** [comment]
Try it!

**Comment by MGelein** [comment]
I have tried it. When I pull it is not included. When I rerun the validation it creates folder and in `git status` it now says it is an untracked file. 

I'm not really sure what the best practice is here. Should I just continue to ignore the untracked file red text screaming at me every `git status` call or should I add the file and then `rm` it again?

**Comment by neelsmith** [comment]
This is all exactly right.  Let scala create the project folder, and ignore.  It's just temporary work space.  don't put it in the repository.

**Comment by MGelein** [comment]
Ok. I think I get it. But if I would for example like to ignore that specific folder I could put it in `gitignore` if my googling skills are correct.

I'm just having trouble ignoring the glaring red text that is telling me the folder is untracked.

**Comment by neelsmith** [comment]
Yes to both.

Let's take a look at that together on Monday.
